import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--color-primary)",
          dark: "var(--color-primary-dark)",
        },
        accent: "var(--color-accent)",
        background: "var(--color-background)",
        text: "var(--color-text)",
        surface: "var(--color-surface)",
        border: "var(--color-border)",
        highlight: "var(--color-highlight)",
        // Olive and Gold theme colors
        ivory: "var(--color-ivory)",
        champagne: "var(--color-champagne)",
        olive: "var(--color-olive)",
        lightOlive: "var(--color-light-olive)",
        darkOlive: "var(--color-dark-olive)",
        gold: "var(--color-gold)",
        goldLight: "var(--color-gold-light)",
        goldDark: "var(--color-gold-dark)",
        warmGray: "var(--color-warm-gray)",
        darkWarmGray: "var(--color-dark-warm-gray)",
      },
      backgroundColor: {
        primary: "var(--color-primary)",
        primaryDark: "var(--color-primary-dark)",
        accent: "var(--color-accent)",
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        ivory: "var(--color-ivory)",
        champagne: "var(--color-champagne)",
        olive: "var(--color-olive)",
        lightOlive: "var(--color-light-olive)",
        darkOlive: "var(--color-dark-olive)",
        gold: "var(--color-gold)",
        goldLight: "var(--color-gold-light)",
        goldDark: "var(--color-gold-dark)",
        warmGray: "var(--color-warm-gray)",
        darkWarmGray: "var(--color-dark-warm-gray)",
      },
      textColor: {
        primary: "var(--color-primary)",
        primaryDark: "var(--color-primary-dark)",
        accent: "var(--color-accent)",
        background: "var(--color-background)",
        text: "var(--color-text)",
        surface: "var(--color-surface)",
        border: "var(--color-border)",
        highlight: "var(--color-highlight)",
        ivory: "var(--color-ivory)",
        champagne: "var(--color-champagne)",
        olive: "var(--color-olive)",
        lightOlive: "var(--color-light-olive)",
        darkOlive: "var(--color-dark-olive)",
        gold: "var(--color-gold)",
        goldLight: "var(--color-gold-light)",
        goldDark: "var(--color-gold-dark)",
        warmGray: "var(--color-warm-gray)",
        darkWarmGray: "var(--color-dark-warm-gray)",
      },
      borderColor: {
        primary: "var(--color-primary)",
        primaryDark: "var(--color-primary-dark)",
        accent: "var(--color-accent)",
        background: "var(--color-background)",
        text: "var(--color-text)",
        surface: "var(--color-surface)",
        border: "var(--color-border)",
        highlight: "var(--color-highlight)",
        ivory: "var(--color-ivory)",
        champagne: "var(--color-champagne)",
        olive: "var(--color-olive)",
        lightOlive: "var(--color-light-olive)",
        darkOlive: "var(--color-dark-olive)",
        gold: "var(--color-gold)",
        goldLight: "var(--color-gold-light)",
        goldDark: "var(--color-gold-dark)",
        warmGray: "var(--color-warm-gray)",
        darkWarmGray: "var(--color-dark-warm-gray)",
      },
      boxShadow: {
        "gold": "0 4px 14px 0 rgba(184, 134, 11, 0.25)",
        "gold-glow": "0 0 20px rgba(184, 134, 11, 0.3)",
      },
      backgroundImage: {
        "gold-gradient": "linear-gradient(90deg, #B8860B, #DAA520)",
        "luxury-gradient": "linear-gradient(135deg, #FAF9F6 0%, #F5EDE4 100%)",
        "olive-gradient": "linear-gradient(135deg, #556B2F 0%, #6B8E23 100%)",
      },
    },
  },
  plugins: [],
};

export default config;
